---
title: "DataExploration"
output: html_document
date: "2023-08-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(tidyverse)
```

## Feature distributions

```{r load data}
drivers <- read.csv('drivers_min_bad_driver.csv')
summary(drivers)
str(drivers)
```

```{r missing values}
missing_summary <- drivers %>%
  summarise_all(~ mean(is.na(.)) * 100) %>%
  gather(variable, missing_percentage)
print(missing_summary)
head(drivers)
```

```{r Box plots of features}
# Load necessary library for plotting
library(ggplot2)

# Features to plot
features_to_plot <- c("TotalClaimsCost", "NumberOfClaims", "OverSpeed", 
                      "IdleRatio", "GpsLostCount", "TelematicsOffCount", 
                      "AverageNmrStopsPerDay", "AverageDistPerStop", 
                      "EmergencyBraking", "NormalBraking", 
                      "HarshBraking", "CriticalBraking")

# Create boxplots for all features
for (feature in features_to_plot) {
  x = ggplot(drivers, aes(x = "", y = get(feature))) +
    geom_boxplot() +
    labs(title = paste("Boxplot of", feature),
         y = feature) +
    theme_minimal() +
    theme(axis.title.x = element_blank())
  print(x)
}

```
